### PR TITLE
chore(syntax) some formatting fixes

### PR DESCRIPTION
**Pull request by thefosk**
ping @Tieske for review

### CODE REVIEW

**Comment by Tieske** [comment]
Actually I use the trailing comma's almost always by default these days. I was actually going to suggest we use them standard within Mashape.

Reason is that I hate those ugly diffs;
screen shot 2016-09-18 at 21 33 56

If it had had a trailing comma, the above would have been a single line diff, now it's a three line diff. @thibaultcha any thoughts?

**Comment by thibaultcha** [comment]
Yeah that's fine

**Comment by thibaultcha** [comment]
Also when missing trailing commas luacov has a bad tendency to count the line as uncovered, which is really annoying. Not that we have coverage setup anymore though.

**Comment by Tieske** [comment]
ok, not merging this. And using trailing comma's going forward.

**Pull request closed without merging**
